repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: '\.(yml|md)$'  # Ignore .yml and .md files
      - id: end-of-file-fixer
        exclude: '\.(yml|md)$'  # Ignore .yml and .md files
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black